Added Total value in Pools
galacticcouncil/HydraDX-ui pull request #193
Opened 2023-01-31 09:17 UTC by vkulinich-cl

Fix #173

2023-01-31 10:23 UTC, tomashapl1 requested changes

2023-01-31 10:23 UTC, tomashapl1 commented on src/sections/wallet/assets/WalletAssetsHeader.tsx
> +  disconnected?: boolean
Could you please let `disableAnimation` prop ? makes more sense for me

2023-02-01 13:13 UTC, jak-pan approved these changes
Tested LGTM once the comments are resolved we can drop this into beta

2023-02-03 13:06 UTC, dqbd approved these changes

2023-02-03 16:41 UTC, merged