fix(HYDRA-361): New transaction type
galacticcouncil/HydraDX-ui pull request #239
Opened 2023-03-06 11:43 UTC by tomashapl1

2023-03-06 12:28 UTC, dqbd commented
Neprovedly se ty změny už tady? https://github.com/galacticcouncil/HydraDX-ui/pull/215/files

2023-03-06 12:30 UTC, tomashapl1 commented
> Neprovedly se ty změny už tady? https://github.com/galacticcouncil/HydraDX-ui/pull/215/files

JJ akorát byl tam navíc za mě zbytečný refactoring, v tomto MR je to udělané, jednodušeji

2023-03-06 12:31 UTC, dqbd requested changes

2023-03-06 12:31 UTC, dqbd commented on src/sections/transaction/ReviewTransaction.utils.ts
> +          setTimeout(() => {
Vyčistit tento timeout při unmountu nebo pokud dojde k resolve

2023-03-09 22:41 UTC, tomashapl1 commented on src/sections/transaction/ReviewTransaction.utils.ts
> +          setTimeout(() => {
Done ✅

2023-03-13 09:07 UTC, dqbd approved these changes

2023-03-13 09:07 UTC, merged